import "./globals.css";

import { Geist, Geist_Mono } from "next/font/google";

import { ClerkProvider } from "@clerk/nextjs";
import DesktopSidebar from "@/components/sidebar/DesktopSidebar";
import type { Metadata } from "next";
import MobileSidebar from "@/components/sidebar/MobileSidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <div className="flex bg-beige">
            <DesktopSidebar />
            <MobileSidebar />
            <main className="flex-1 items-center p-[40px] text-gray-900 h-screen pb-[110px] lg:pb-[40px]">
              {children}
            </main>
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
