import "./globals.css";

import { Geist, Geist_Mono } from "next/font/google";

import { ClerkProvider } from "@clerk/nextjs";
import DesktopSidebar from "@/components/sidebar/DesktopSidebar";
import type { Metadata } from "next";
import MobileSidebar from "@/components/sidebar/MobileSidebar";
import { currentUser } from "@clerk/nextjs/server";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await currentUser();

  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <div className="flex bg-beige">
            {user && (
              <>
                <DesktopSidebar />
                <MobileSidebar />
              </>
            )}
            <main
              className={`flex-1 items-center ${
                user ? "p-[2%]" : null
              } text-gray-900 h-screen`}
            >
              {children}
            </main>
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
